const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={shipper:'Shipper',consignee:'Consignee',notify_party:'Notify party',port_of_loading:'Port of loading',port_of_discharge:'Port of discharge',container_count:'Container count',gross_weight_kg:'Gross weight (kg)'};
const states={verified_ok:'Verified match',mismatch:'Discrepancy',needs_review:'Needs review',awaiting_documents:'Waiting',classified:'Classified',processing_failed:'Processing failed'};
let rows=[],selected=null,current=null,health={uploads_enabled:true};let toastTimer;
async function api(url,options){const r=await fetch(url,options);if(!r.ok){let msg=await r.text();try{msg=JSON.parse(msg).detail||msg}catch{}throw Error(typeof msg==='string'?msg:JSON.stringify(msg))}return r.json()}
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4500)}
function badge(state){return `<span class="badge ${esc(state)}">${esc(states[state]||state)}</span>`}
function locator(loc){return Object.entries(loc||{}).filter(([k])=>k!=='bbox').map(([k,v])=>`${k} ${v}`).join(' · ')}
async function refresh(){try{const [data,status]=await Promise.all([api('/api/cases'),api('/api/health')]);health=status;rows=data.cases;$('#runtime-mode').textContent=status.mode;$('#runtime-note').textContent=status.mode.includes('public')?'Shared synthetic sandbox. No organizer documents or ground truth are hosted.':'Private source documents remain in this workspace.';$('#ocr-status').textContent=status.ocr_backend==='unavailable'?'OCR unavailable · human gate active':`${status.ocr_backend.replaceAll('_',' ')} OCR · human-gated`;$('#reset-demo').hidden=!status.mode.includes('public');$('#total').textContent=rows.length;$('#review-count').textContent=(data.counts.needs_review||0)+(data.counts.processing_failed||0);for(const [id,key] of [['m-ok','verified_ok'],['m-mismatch','mismatch'],['m-review','needs_review'],['m-wait','awaiting_documents']])$('#'+id).textContent=(data.counts[key]||0)+(key==='needs_review'?(data.counts.processing_failed||0):0);$('#m-total').textContent=rows.length;renderList();if(!selected){const initial=rows.find(r=>r.state==='mismatch')||rows[0];if(initial)await loadCase(initial.id)}}catch(e){$('#detail').innerHTML=`<div class="empty">Unable to load cases. ${esc(e.message)}<br>Check that the service is running, then refresh.</div>`}}
function renderList(){const q=$('#search').value.toLowerCase(),filter=$('#filter').value;const filtered=rows.filter(r=>(filter==='all'||r.state===filter||filter==='needs_review'&&r.state==='processing_failed')&&`${r.id} ${r.subject} ${r.sender}`.toLowerCase().includes(q));$('#result-count').textContent=`${filtered.length} emails`;$('#case-list').innerHTML=filtered.length?filtered.map(r=>`<button class="case-item ${r.id===selected?'selected':''}" data-case="${esc(r.id)}" aria-label="${esc(r.id)} ${esc(states[r.state])}"><div class="case-meta"><span>${esc(r.id.replace('email_','#'))}</span>${badge(r.state)}</div><h3>${esc(r.subject)}</h3><div class="sender">${esc(r.sender)}</div></button>`).join(''):'<div class="empty">No emails match this filter.</div>';document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>loadCase(b.dataset.case))}
async function loadCase(id){selected=id;renderList();$('#detail').classList.add('loading');try{const loaded=await api('/api/cases/'+encodeURIComponent(id));if(selected!==id)return;current=loaded;renderCase()}catch(e){toast(e.message)}finally{if(selected===id)$('#detail').classList.remove('loading')}}
function valueCell(obs,role,field){if(!obs)return '<span class="empty-value">Document unavailable</span>';return `<div class="value ${obs.raw_value==null?'empty-value':''}">${esc(obs.raw_value??'Value not found')}</div><button class="source-link" data-evidence="${role}:${field}">${esc(obs.method==='human_review'?'Human-confirmed · ':obs.method?.endsWith('_ocr')?'AI OCR suggestion · ':'')}${esc(obs.reviewer_source_location||locator(obs.locator)||'View source')} ↗</button>`}
function renderCase(){const c=current,isDoc=c.classification.category==='BL_COMPARISON';const title=c.workflow_state==='mismatch'?`${c.known_defects.length} field${c.known_defects.length===1?' needs':'s need'} attention`:c.workflow_state==='processing_failed'?'Processing failed: retry or replace source':c.workflow_state==='needs_review'?'Human input required':c.workflow_state==='awaiting_documents'?'Waiting for source documents':c.workflow_state==='verified_ok'?'No mismatch detected':'Routed to '+c.classification.category.replaceAll('_',' ').toLowerCase();$('#detail').innerHTML=`
 <div class="detail-top"><span class="case-id">${esc(c.email_id)} / ${esc(c.classification.category)}</span><span class="version">Report v${c.report_version}</span></div><h2 class="subject">${esc(c.email.subject)}</h2><div class="email-meta">From ${esc(c.email.from)} · ${c.email.attachments.length} attachment${c.email.attachments.length===1?'':'s'}</div>
 <div class="decision ${esc(c.workflow_state)}"><strong>${esc(title)}</strong><p>${esc(c.decision_reason||c.classification.reason)}</p>${c.export_note?'<p>Not verified. This request is waiting for documents.</p>':''}</div>
 <div class="action-row">${isDoc?`<button class="button primary" id="open-review">Review a field</button>${health.uploads_enabled?'<button class="button secondary" id="open-upload">Add / replace document</button>':''}<button class="button secondary" id="retry">↻ Recheck</button>`:''}<a class="button secondary" href="/api/cases/${encodeURIComponent(c.email_id)}/report">Export report ↗</a></div>
 ${isDoc?`<div class="section-title"><h3>Seven-field verification</h3><span>SI is the reference</span></div><div class="field-table"><div class="field-row table-head"><div>FIELD</div><div>SHIPPING INSTRUCTION</div><div>DRAFT BILL OF LADING</div><div>RESULT</div></div>${c.comparisons.map(x=>`<div class="field-row row-${x.state.toLowerCase()}"><div class="field-name">${labels[x.field]}</div><div>${valueCell(x.SI,'SI',x.field)}</div><div>${valueCell(x.BL,'BL',x.field)}</div><div>${badge(x.state)}<button class="review-link" data-review="${x.field}">Review →</button></div></div>`).join('')}</div>`:''}
 <div class="section-title"><h3>Source documents</h3><span>Original evidence retained</span></div>${c.documents.length?c.documents.map((d,i)=>`<div class="doc-row"><span class="doc-icon">${esc(d.format.toUpperCase())}</span><div class="doc-name">${esc(d.file.split('/').pop())}<small>${esc(d.role==='UNKNOWN'?'Role unconfirmed':d.role)} · ${esc(d.method.replaceAll('_',' '))}${d.errors.length?' · Reading issue':''}</small></div><button class="text-button" data-document="${i}">Inspect ↗</button></div>`).join(''):'<p class="muted">No documents processed for this email.</p>'}
 <details class="disclosure"><summary>Email & routing evidence</summary><p>${esc(c.classification.reason)}</p><blockquote>${esc(c.classification.evidence)}</blockquote><pre>${esc(c.email.body)}</pre></details>
 <details class="disclosure" ${c.review_events.length?'open':''}><summary>Review history · ${c.review_events.length} event${c.review_events.length===1?'':'s'}</summary>${c.review_events.length?c.review_events.map(e=>`<div class="audit-event"><strong>v${e.version} · ${esc(e.action.replaceAll('_',' '))}${e.field?' · '+esc(e.role)+' '+labels[e.field]:''}</strong><small>${esc(e.reviewer)} · ${new Date(e.timestamp).toLocaleString()}</small><p>${esc(e.reason)}</p>${e.before?`<p>${esc(e.before.raw_value??'Missing')} → <strong>${esc(e.after.raw_value)}</strong></p>`:''}${e.preserved_corrections?.length?`<small>Retained ${e.preserved_corrections.length} human correction(s).</small>`:''}</div>`).join(''):'<p class="muted">No human changes. Original automatic prediction is preserved separately.</p>'}</details>`;
 document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>{const [role,field]=b.dataset.evidence.split(':');showEvidence(role,field)});document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>openReview(b.dataset.review));document.querySelectorAll('[data-document]').forEach(b=>b.onclick=()=>showDocument(Number(b.dataset.document)));if(isDoc){$('#open-review').onclick=()=>openReview(c.unresolved_fields[0]||c.known_defects[0]||'shipper');if($('#open-upload'))$('#open-upload').onclick=openUpload;$('#retry').onclick=retry}}
function showEvidence(role,field){const obs=current.fields[role][field];const index=current.documents.findIndex(d=>d.file===obs.source_file);$('#evidence-title').textContent=`${role} · ${labels[field]}`;const original=obs.original_observation||obs;$('#evidence-content').innerHTML=`<p class="muted">${esc(obs.source_file)} · ${esc(locator(obs.locator))}</p><div class="evidence-quote">${esc(original.evidence||'No value was extracted at this location. Inspect the full document.')}</div><div class="evidence-rule"><strong>Normalization</strong><br>${esc(obs.normalization)}<br><small>Normalized value: ${esc(obs.normalized_value??'Unresolved')}</small></div>${obs.method==='human_review'?`<p class="muted">Human correction: ${esc(obs.raw_value)}. ${esc(obs.review_reason)} Source checked: ${esc(obs.reviewer_source_location||locator(obs.locator))}</p>`:''}${previewHTML(index,obs.locator)}${linesHTML(index,obs.locator)}`;$('#evidence-dialog').showModal()}
function previewHTML(index,loc={}){const doc=current.documents[index];if(!doc||doc.format!=='pdf')return '';const b=loc.bbox;return `<div class="page-preview"><img src="/api/cases/${encodeURIComponent(current.email_id)}/preview/${index}/${loc.page||1}" alt="Original PDF page" onerror="this.replaceWith(document.createTextNode('This PDF cannot be rendered. Replace the damaged file.'))">${b?`<div class="highlight" style="left:${b[0]*100}%;top:${b[1]*100}%;width:${b[2]*100}%;height:${b[3]*100}%"></div>`:''}</div>`}
function linesHTML(index,loc={}){const doc=current.documents[index];if(!doc)return '';return `<div class="source-lines">${doc.lines.map(l=>`<div class="source-line ${JSON.stringify(l.locator)===JSON.stringify(loc)?'focus':''}"><span class="muted">${esc(locator(l.locator))}</span> ${esc(l.text)}</div>`).join('')}</div><p class="muted">Source SHA-256: ${esc(doc.sha256||'Unavailable')}</p>`}
function showDocument(index){const d=current.documents[index];$('#evidence-title').textContent=d.file.split('/').pop();$('#evidence-content').innerHTML=`<p>${esc(d.role)} · ${esc(d.method.replaceAll('_',' '))}</p>${d.errors.map(e=>`<p class="form-error">${esc(e)}</p>`).join('')}<a class="button secondary" href="/api/cases/${encodeURIComponent(current.email_id)}/document/${index}" target="_blank" rel="noopener">Open original file ↗</a>${previewHTML(index)}${linesHTML(index)}`;$('#evidence-dialog').showModal()}
function openReview(field){$('#review-field').innerHTML=Object.entries(labels).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');$('#review-field').value=field;const available=Object.keys(current.fields);if(!available.length){toast('Add or replace a readable SI/BL before reviewing fields.');return}$('#review-role').innerHTML=available.map(r=>`<option>${r}</option>`).join('');$('#review-role').value=available.find(r=>{const o=current.fields[r][field];return o.warning||o.requires_confirmation&&!o.confirmed})||(available.includes('BL')?'BL':available[0]);$('#review-error').textContent='';$('#review-form [name=reason]').value='';updateReviewValue();$('#review-dialog').showModal()}
function updateReviewValue(){const o=current.fields[$('#review-role').value]?.[$('#review-field').value];$('#review-value').value=o?.raw_value||'';$('#source-location').value=o?.reviewer_source_location||locator(o?.locator);$('#source-location').required=!Object.keys(o?.locator||{}).length;$('#review-source').textContent=`${o?.source_file||''}\n${locator(o?.locator)}\n${o?.evidence||'Missing source value. Enter a value only after checking the document.'}`}
$('#review-role').onchange=updateReviewValue;$('#review-field').onchange=updateReviewValue;
$('#review-form').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('[type=submit]');btn.disabled=true;try{const body=Object.fromEntries(new FormData(e.target));body.expected_version=current.report_version;current=await api(`/api/cases/${encodeURIComponent(selected)}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('#review-dialog').close();renderCase();await refresh();toast(`Saved. Report v${current.report_version} recomputed.`)}catch(err){$('#review-error').textContent=err.message}finally{btn.disabled=false}};
function openUpload(){$('#replace-file').innerHTML='<option value="">Add a missing document</option>'+current.email.attachments.map(f=>`<option value="${esc(f)}">${esc(f.split('/').pop())}</option>`).join('');$('#upload-error').textContent='';$('#upload-dialog').showModal()}
$('#upload-form').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('[type=submit]');btn.disabled=true;try{const form=new FormData(e.target);form.append('expected_version',current.report_version);current=await api(`/api/cases/${encodeURIComponent(selected)}/upload`,{method:'POST',body:form});$('#upload-dialog').close();renderCase();await refresh();toast('Document saved and rechecked.')}catch(err){$('#upload-error').textContent=err.message}finally{btn.disabled=false}};
async function retry(){const btn=$('#retry');btn.disabled=true;btn.textContent='Rechecking…';try{current=await api(`/api/cases/${encodeURIComponent(selected)}/retry`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_version:current.report_version,reviewer:$('#reviewer-name').value,reason:'Rechecked source documents; preserve confirmed corrections.'})});renderCase();await refresh();toast('Recheck complete. Human corrections retained where sources are unchanged.')}catch(e){toast(e.message);btn.disabled=false;btn.textContent='↻ Recheck'}}
$('#search').oninput=renderList;$('#filter').onchange=renderList;$('#refresh').onclick=async()=>{await refresh();if(selected)await loadCase(selected)};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{$('#filter').value=b.dataset.filter;document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.filter===b.dataset.filter));renderList()});for(const name of ['evidence','review','upload'])$('#close-'+name).onclick=()=>$('#'+name+'-dialog').close();refresh();
document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=()=>loadCase(b.dataset.scenario));$('#reset-demo').onclick=async()=>{if(!confirm('Reset the shared synthetic sandbox to its original reports?'))return;await api('/api/demo/reset',{method:'POST'});selected=null;current=null;await refresh();toast('Synthetic demo restored.')};
